triggers:
- envs: []
  last_enabled_at: 2024-04-06 19:04:52.851972
  name: nightly_covid_data_pull
  pipeline_uuid: de_project_coviddata
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-04-06 23:00:00
  status: active
  variables: {}
